export default {
    title: 'Task Management System',
    addTask: 'Add Task',
    taskTitle: 'Task Title:',
    taskDescription: 'Task Description:',
    deadline: 'Deadline:',
    category: 'Category:',
    tags: 'Tags:',
    priority: 'Priority:',
    taskProgress: 'Task Progress:',
    comments: 'Comments:',
    attachments: 'Attachments:',
    saveTask: 'Save Task',
    exportTasks: 'Export Tasks',
    importTasks: 'Import Tasks',
    toggleDarkMode: 'Toggle Dark Mode',
    taskList: 'Task List',
    searchTasks: 'Search Tasks...',
    allCategories: 'All Categories',
    allTags: 'All Tags',
    allTasks: 'All Tasks',
    completed: 'Completed',
    incomplete: 'Incomplete',
    work: 'Work',
    personal: 'Personal',
    shopping: 'Shopping',
    other: 'Other',
    home: 'Home',
    health: 'Health',
    study: 'Study',
    entertainment: 'Entertainment',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    chooseFile: 'Choose file'
};
